### ISSUE TITLE
Ap++ and SkyX not working

### ISSUE THREAD

**Issue by DemonzTimexs** [geofs-plugins/plugin-manager#1]
![image](https://user-images.githubusercontent.com/29449907/27171233-7fe65478-51ce-11e7-8fbe-2d5b5e622587.png)
I am using AP++ and SkyX with tampermonkey
From Last few days it's not working
I am using the latest version of AP++ and SkyX i am using via Tampermonkey
I can't use the Chrome WebStore one SkyX extension because due to problem in GeoFS i use GeoFS in incognito

**Comment by yotam180** [comment]
Did you try enabling the extension in the incognito mode using [this ](http://www.tomsguide.com/faq/id-2384484/enable-disable-chrome-extensions-incognito-mode.html) guide?

We don't _officially_ support any further the TamperMonkey version, but if you still have problems we'll investigate this problem furthermore.

Please reply with the result of the extension in incognito mode.

Thanks,
Yotam.

**Comment by DemonzTimexs** [comment]
@yotam180
Thanks for your ans!
Please note that I already enabled that before and am aware of it.
Note that i was using SkyX extension before and some problem occur in GeoFS and from that day it is not working. 
And note that ap++ is fixed for me. I updated it to 10.6 version
The only problem now is SkyX extension via tampermonkey

**Comment by yotam180** [comment]
I'm closing this as the **SkyX** extension is now history. When the new plugin manager comes out, we'll make sure this problem is solved.

**Comment by DemonzTimexs** [comment]
![image](https://user-images.githubusercontent.com/29449907/27260155-6109b47a-5442-11e7-94c2-4421471cc04b.png)
@yotam180 FYI

**Comment by yotam180** [comment]
Try reloading the plugin again. I tried to make the extension loading wait to **$** (jQuery) so it's defined when aircraft-loader is loaded.

Thanks,
Yotam.

**Comment by DemonzTimexs** [comment]
Just wanna confirm you people that's it's still not working.

Sincerely
Demonz.

**Comment by yotam180** [comment]
**Reference:** Same issue, more detailed. I'm closing here in favour of #2
